package lk.ijse.aad.backend.entity;

public enum NotificationType {
    TASK_ASSIGNED,
    PROPOSAL_UPDATE,
    DEADLINE_REMINDER,
    PAYMENT_RECEIVED,
    PAYMENT_RELEASED,
    PAYMENT_FAILED,
    REVIEW_POSTED,
    USER_REGISTERED,
    TASK_CREATED,
    PROPOSAL_CREATED,
    WORK_SUBMITTED
}
